---
- gather_facts: true
  hosts: aws_ec2
  become: true
  roles:
    - role: common
      vars:
         container_count: 1
         default_container_name: nginx
         default_container_image: nginx
         default_container_command: sleep 1d
